entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"

providers:
  docker: {}

certificatesResolvers:
  myresolver:
    acme:
      email: istehedef@gmail.com
      storage: /data/letsencrypt.json
      httpChallenge:
        entryPoint: web
